apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zro-pipeline
spec:
  workspaces:
  - name: workspace
  tasks:
    - name: hello
      workspaces:
      - name: workspace
        workspace: workspace
      taskRef:
        name: hello
    - name: lint
      workspaces:
      - name: workspace
        workspace: workspace
      runAfter: 
        - hello
      taskRef:
        name: golangci-lint
    - name: test
      workspaces:
      - name: workspace
        workspace: workspace
      runAfter: 
        - lint
      taskRef:
        name: golang-test
